server:
  port: 8083

spring:
  data:
    mongodb:
      url: mongodb://localhost::27017
      database: mcsvratings

  application:
    name: RATING-SERVICE

eureka:
  instance:
    prefer-ip-address: true #muestra las ip de los servicios en vez de los nombres
  client:
    fetch-registry: true #registra el servidor cliente
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka #apunta al mismo host de aureka, 8761 es el port por defecto de aureka
